Repository acesdit/snippets, pull requests merged in 2023-10, with the labels that each got.

#10 Create Heap sort.cpp
  ALGORITHMS/Heap Sort.cpp
Labels: on hold

#11 QuickSort Algorithm
  ALGORITHMS/Quick Sort.cpp
Labels: on hold

#58 Create Stack.cpp
  DATA STRUCTURES/Stack STL.cpp
Labels: on hold, changes requested

#89 hide scrollbars
  src/components/CategorySelector.astro
  src/components/LanguageSelector.astro
  src/layouts/BaseLayout.astro
Labels: changes requested

#130 Create johnsonsAgorithm.cpp
  ALGORITHMS/johnsonsAgorithm.cpp
Labels: changes requested

#117 Password generator .py
  ALGORITHMS/Password Generator Algorithm.py
Labels: changes requested

#118 Add two complex numbers.cpp
  ALGORITHMS/Addition of two complex numbers.cpp
Labels: changes requested

#125 Create Copycat.md
  INTERVIEW QUESTIONS/Copycat.md
Labels: changes requested

#126 Create uglyNumbers.md
  INTERVIEW QUESTIONS/Ugly Numbers.md
Labels: changes requested
